// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriView.Server.Data;

#nullable disable

namespace NutriView.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240119143949_DBRedo")]
    partial class DBRedo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.Key", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DataProtected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsX509Certificate")
                        .HasColumnType("bit");

                    b.Property<string>("Use")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Use");

                    b.ToTable("Keys", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("ConsumedTime");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0afa81d9-cb31-4883-ae16-c9d0242e3440",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "a1329842-8556-4ee7-ae1a-fd648064c54a",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "428fdfc4-086b-4aba-bb98-148f31eaa143",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "f5a29727-ea9d-41d4-9175-dd1fb6ec2755",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8aa738a7-6c07-4e5a-8a7f-5637388c41b4",
                            RoleId = "0afa81d9-cb31-4883-ae16-c9d0242e3440"
                        },
                        new
                        {
                            UserId = "41624b27-7496-447c-b299-4892483d6b47",
                            RoleId = "a1329842-8556-4ee7-ae1a-fd648064c54a"
                        },
                        new
                        {
                            UserId = "1507dbd1-1c83-4ad2-9b0e-4d298c7b4521",
                            RoleId = "428fdfc4-086b-4aba-bb98-148f31eaa143"
                        },
                        new
                        {
                            UserId = "4d3dfcba-a0af-4b10-989d-d63dcfec5e97",
                            RoleId = "f5a29727-ea9d-41d4-9175-dd1fb6ec2755"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NutriView.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8aa738a7-6c07-4e5a-8a7f-5637388c41b4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d23cec03-3ed6-40c5-81ca-57ac139a5bc3",
                            Email = "admin@localhost.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDv4sbnnd7nWUXm5nNcq1eP2XV1ORC6PC/4SBslLoPnRt367d0HnPtfA5b4Amlq7MQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b497b0ca-d85d-4804-bccb-6fa5f8ac5a91",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "41624b27-7496-447c-b299-4892483d6b47",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "33ae445b-ccfc-4d37-9e7e-88b3300fd40d",
                            Email = "Customer@localhost.com",
                            EmailConfirmed = false,
                            FirstName = "Customer",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "Customer@LOCALHOST.COM",
                            NormalizedUserName = "CUSTOMER@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKJNEMfE/lHnkar4kP4LzarOOR9C5pY9BjWfXT95kovr5F+1gucdrOLbPrNnczS4Mw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fca5e093-08fd-453a-a6bf-87ce3bcc3983",
                            TwoFactorEnabled = false,
                            UserName = "Customer@localhost.com"
                        },
                        new
                        {
                            Id = "1507dbd1-1c83-4ad2-9b0e-4d298c7b4521",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f9960669-6e22-4284-9985-3156997f0307",
                            Email = "Manager@localhost.com",
                            EmailConfirmed = false,
                            FirstName = "Manager",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "Manager@LOCALHOST.COM",
                            NormalizedUserName = "MANAGER@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMLVdjOsEjTRIdR/V0mMVRArr/tiLQdz2+s1oknUKsbaPhvh6W/n5dzR08EXht4w5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "811f21dd-7c6a-4c42-bd2d-2014a3b7d7fc",
                            TwoFactorEnabled = false,
                            UserName = "Manager@localhost.com"
                        },
                        new
                        {
                            Id = "4d3dfcba-a0af-4b10-989d-d63dcfec5e97",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bebc9cea-7309-4f22-b053-7c6dc8c65a0b",
                            Email = "Staff@localhost.com",
                            EmailConfirmed = false,
                            FirstName = "Staff",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "Staff@LOCALHOST.COM",
                            NormalizedUserName = "STAFF@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE7HKA62ZykWUiv3mmeOYdgMaWEeq2AZoFJcqdJ0KU5js/awmUy/1Z4kx5bcJN6F9w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ce66f67b-d66d-4667-8a1b-d2e405ac4896",
                            TwoFactorEnabled = false,
                            UserName = "Staff@localhost.com"
                        });
                });

            modelBuilder.Entity("NutriView.Shared.Domain.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyDescription = "At NuriView Corporations, we believe that a heathy lifestyle would always begins with proper nutrition.We are a dedicated team of nutritionists and dietitians comitted in providing you with the knowledge and tools to aid you in your journey to a healthier diet.",
                            CompanyImagePath = "Not Yet Available",
                            CompanyName = "NutriView",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(2731),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(2732),
                            Mission = "Our mission is to empower individuals to achieve optimal health through mindful eating. We understand that nutrition is not always a one-size-fits-all.Our goal is to guide you on a personalized journey towards a balanced and nourishing lifestyle that will bring you a step closer to a healthier you.",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CompanyDescription = "Not Yet Available",
                            CompanyImagePath = "Not Yet Available",
                            CompanyName = "NutriViewCorps",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(2734),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(2734),
                            Mission = "Our Mission is to encourage people to eat healthy and live healthy",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("NutriView.Shared.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 31,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5445),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5456),
                            Email = "Test@Blazor.com",
                            Gender = "Male",
                            Height = 160.0,
                            Password = "Test222",
                            UpdatedBy = "System",
                            UserName = "TestLim",
                            Weight = 88.5
                        },
                        new
                        {
                            Id = 2,
                            Age = 32,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5459),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5460),
                            Email = "Test2@Blazor.com",
                            Gender = "Female",
                            Height = 178.0,
                            Password = "Test2212",
                            UpdatedBy = "System",
                            UserName = "TestRRLim",
                            Weight = 77.0
                        });
                });

            modelBuilder.Entity("NutriView.Shared.Domain.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("float");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("Fats")
                        .HasColumnType("float");

                    b.Property<string>("FoodDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodEntryID")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ServingSize")
                        .HasColumnType("float");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vitamins")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoodEntryID");

                    b.HasIndex("StaffId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 25.0,
                            Carbohydrates = 6.0,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(3059),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(3060),
                            Fats = 0.10000000000000001,
                            FoodDesc = "Carrots Contains 25 Calories and 6g of Carbohydrates , etc",
                            FoodEntryID = 1,
                            ImagePath = "-",
                            Name = "Carrots",
                            ServingSize = 61.0,
                            StaffId = 1,
                            UpdatedBy = "System",
                            Vitamins = "A,C,K"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 165.0,
                            Carbohydrates = 0.0,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(3062),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(3062),
                            Fats = 3.6000000000000001,
                            FoodDesc = "Chicken Contains 165 Calories per 100 grams and does not have any Carbohydrates , etc",
                            FoodEntryID = 2,
                            ImagePath = "-",
                            Name = "Chicken",
                            ServingSize = 100.0,
                            StaffId = 2,
                            UpdatedBy = "System",
                            Vitamins = "A, B6, C, D, E"
                        });
                });

            modelBuilder.Entity("NutriView.Shared.Domain.FoodEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Time_Stamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalCalories")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.ToTable("FoodEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CustomerID = 1,
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5942),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5943),
                            Time_Stamp = "22 Jan 2024",
                            TotalCalories = 22.0,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CustomerID = 2,
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5945),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5945),
                            Time_Stamp = "1 Jan 2024",
                            TotalCalories = 34.0,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("NutriView.Shared.Domain.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodEntryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PortionSize")
                        .HasColumnType("float");

                    b.Property<string>("TimePeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoodEntryID");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 19, 14, 39, 49, 176, DateTimeKind.Utc).AddTicks(6276),
                            DateUpdated = new DateTime(2024, 1, 19, 14, 39, 49, 176, DateTimeKind.Utc).AddTicks(6281),
                            FoodEntryID = 1,
                            Name = "Carrots",
                            PortionSize = 1.0,
                            TimePeriod = "Morning",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 19, 14, 39, 49, 176, DateTimeKind.Utc).AddTicks(6282),
                            DateUpdated = new DateTime(2024, 1, 19, 14, 39, 49, 176, DateTimeKind.Utc).AddTicks(6283),
                            FoodEntryID = 2,
                            Name = "ChickenRice",
                            PortionSize = 1.0,
                            TimePeriod = "Morning",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("NutriView.Shared.Domain.NutritionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("NutritionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutritionImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutritionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("NutritionInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(2898),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(2898),
                            NutritionDescription = "Essential for vision, immune function, and skin health.",
                            NutritionImagePath = "-",
                            NutritionName = "Vitamin A",
                            StaffId = 1,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(2900),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(2900),
                            NutritionDescription = "Supports bone health, immune system, and overall well-being.",
                            NutritionImagePath = "-",
                            NutritionName = "Vitamin D",
                            StaffId = 2,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("NutriView.Shared.Domain.NutritionalQuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("TargetBMI")
                        .HasColumnType("float");

                    b.Property<double>("TargetCalorieDaily")
                        .HasColumnType("float");

                    b.Property<double>("TargetCarbDaily")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.ToTable("NutritionalQuotas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CustomerID = 1,
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(6527),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(6528),
                            TargetBMI = 19.0,
                            TargetCalorieDaily = 2000.0,
                            TargetCarbDaily = 300.0,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CustomerID = 2,
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(6530),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(6530),
                            TargetBMI = 21.0,
                            TargetCalorieDaily = 2000.0,
                            TargetCarbDaily = 290.0,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("NutriView.Shared.Domain.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePathStaff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(3414),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(3416),
                            Email = "ngchunlim04@gmail.com",
                            ImagePathStaff = "-",
                            ManagerID = 1,
                            Password = "Chun11",
                            PhoneNumber = 87993192,
                            Role = "Manager",
                            UpdatedBy = "System",
                            UserName = "ChunLim"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(3417),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(3418),
                            Email = "Test04@gmail.com",
                            ImagePathStaff = "-",
                            ManagerID = 2,
                            Password = "Lim12",
                            PhoneNumber = 87993192,
                            Role = "Manager",
                            UpdatedBy = "System",
                            UserName = "Kenneth"
                        });
                });

            modelBuilder.Entity("NutriView.Shared.Domain.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubInfoID")
                        .HasColumnType("int");

                    b.Property<int?>("SubscriptionInfoId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.HasIndex("SubscriptionInfoId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 0.0,
                            CreatedBy = "System",
                            CustomerID = 1,
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5743),
                            DateEnd = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5741),
                            DateStart = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5741),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5743),
                            SubInfoID = 0,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 0.0,
                            CreatedBy = "System",
                            CustomerID = 2,
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5745),
                            DateEnd = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5745),
                            DateStart = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5744),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 49, 176, DateTimeKind.Local).AddTicks(5746),
                            SubInfoID = 0,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("NutriView.Shared.Domain.SubscriptionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("SubCost")
                        .HasColumnType("float");

                    b.Property<string>("SubDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(2397),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(2407),
                            SubCost = 5.0,
                            SubDescription = "Unlocks The Personal Quota Tracker",
                            SubTierName = "Health Enthusiasts",
                            SubType = "Monthly",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(2410),
                            DateUpdated = new DateTime(2024, 1, 19, 22, 39, 48, 987, DateTimeKind.Local).AddTicks(2410),
                            SubCost = 30.0,
                            SubDescription = "Unlocks The Personal Quota Tracker and other Features!!",
                            SubTierName = "Health Enthusiasts",
                            SubType = "Yearly",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NutriView.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NutriView.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriView.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NutriView.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriView.Shared.Domain.Food", b =>
                {
                    b.HasOne("NutriView.Shared.Domain.FoodEntry", "FoodEntry")
                        .WithMany("Foods")
                        .HasForeignKey("FoodEntryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriView.Shared.Domain.Staff", "Staff")
                        .WithMany("Foods")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodEntry");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("NutriView.Shared.Domain.FoodEntry", b =>
                {
                    b.HasOne("NutriView.Shared.Domain.Customer", "Customer")
                        .WithMany("Entries")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NutriView.Shared.Domain.Meal", b =>
                {
                    b.HasOne("NutriView.Shared.Domain.FoodEntry", "FoodEntry")
                        .WithMany("Meals")
                        .HasForeignKey("FoodEntryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodEntry");
                });

            modelBuilder.Entity("NutriView.Shared.Domain.NutritionInfo", b =>
                {
                    b.HasOne("NutriView.Shared.Domain.Staff", "Staff")
                        .WithMany("NutritionInfos")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("NutriView.Shared.Domain.NutritionalQuota", b =>
                {
                    b.HasOne("NutriView.Shared.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NutriView.Shared.Domain.Staff", b =>
                {
                    b.HasOne("NutriView.Shared.Domain.Company", "Company")
                        .WithMany("Staffs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NutriView.Shared.Domain.Subscription", b =>
                {
                    b.HasOne("NutriView.Shared.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriView.Shared.Domain.SubscriptionInfo", "SubscriptionInfo")
                        .WithMany()
                        .HasForeignKey("SubscriptionInfoId");

                    b.Navigation("Customer");

                    b.Navigation("SubscriptionInfo");
                });

            modelBuilder.Entity("NutriView.Shared.Domain.Company", b =>
                {
                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("NutriView.Shared.Domain.Customer", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("NutriView.Shared.Domain.FoodEntry", b =>
                {
                    b.Navigation("Foods");

                    b.Navigation("Meals");
                });

            modelBuilder.Entity("NutriView.Shared.Domain.Staff", b =>
                {
                    b.Navigation("Foods");

                    b.Navigation("NutritionInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
